apiVersion: v1
kind: Service
metadata:
  name: pruebageneral-ds
spec:
  selector:
    app: prueba_holamundo
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pruebageneral-ds
spec:
  selector:
    matchLabels:
      app: prueba_holamundo
  replicas: 5
  template:
    metadata:
      labels:
        app: prueba_holamundo
    spec:
      containers:
      - name: pruebageneral-ds
        image: prueba_holamundo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000